spring:
  datasource:
    url: jdbc:mysql://localhost/db_springboot_backend?useSSL=false&serverTimezone=America/Mexico_City
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  jackson:
    time-zone: America/Mexico_City
    locale: es_MX
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org:
      hibernate:
        SQL: debug 

      
